board: MKS DLC32 2.0
name: MKS DLC32 XYZ
meta: Buttons and Relays v0.6 (27/01/2023)
stepping:
  engine: I2S_stream
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 5
  disable_delay_us: 0
  segments: 6
axes:
  shared_stepper_disable_pin: I2SO.0
  x:
    steps_per_mm: 1280.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 341.000
    soft_limits: true
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_all_pin: gpio.36
      hard_limits: true
      pulloff_mm: 0.5000
      standard_stepper:
        step_pin: I2SO.1
        direction_pin: I2SO.2
  y:
    steps_per_mm: 1280.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 435.000
    soft_limits: true
    homing:
      cycle: 3
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_all_pin: gpio.35
      hard_limits: true
      pulloff_mm: 0.5000
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.6
  z:
    steps_per_mm: 1280.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 163.000
    soft_limits: true
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_all_pin: gpio.34
      hard_limits: true
      pulloff_mm: 0.5000
      standard_stepper:
        step_pin: I2SO.3
        direction_pin: I2SO.4
kinematics:
  Cartesian:
i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17
spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14
sdcard:
  cs_pin: gpio.15
  card_detect_pin: NO_PIN
control:
  safety_door_pin: NO_PIN
  reset_pin: gpio.18
  feed_hold_pin: gpio.19
  cycle_start_pin: gpio.23
  macro0_pin: gpio.32
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
coolant:
  flood_pin: gpio.25
  mist_pin: gpio.26
  delay_ms: 50
probe:
  pin: gpio.22
  check_mode_start: true
macros:
  startup_line0: 
  startup_line1:
#HOME: retract, stop and move to location G28
  macro0: G90 G53 G0Z0 & M9 M5 & G28
  macro1:
  macro2: 
  macro3: 
start:
  must_home: false
  deactivate_parking: false
  check_limits: false
user_outputs:
#gpio.4 (LC/Spindle) has a high current open collector output on the MKS board
  analog0_pin: gpio.4
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: gpio.5
#i2so.7 (BEEPER) has a medium current open collector output on the mks board
  digital1_pin: I2SO.7
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16
Huanyang:
  uart:
    txd_pin: gpio.27
    rxd_pin: gpio.33
    rts_pin: NO_PIN
    baud: 9600
    mode: 8N1
  modbus_id: 1
  tool_num: 0
  speed_map: 0=0% 0=1% 240=1% 24000=100%
  